const mongoose = require('mongoose');
const mongoosePaginate = require('mongoose-paginate-v2');

/**
 * @swagger
 * components:
 *  schemas:
 *      Category:
 *          properties:
 *              _id:
 *                  type: ObjectId
 *                  description: Auto-generated Id of the category
 *              name:
 *                  type: string
 *                  description: Name of the category
 *              slug:
 *                  type: string
 *                  description: Autogenerated unique characters which identifies the resource being served
 *              status:
 *                  type: string
 *                  description: Status of the category - active, deactive and pending.
 *          example:
 *              _id: ObjectId(61bac88e4ac42802a721a9a4)
 *              name: Education
 *              slug: education
 *              status: active
 */

const schema = new mongoose.Schema(
    {
        _id: mongoose.Schema.Types.ObjectId,
        name: {
            type: String,
            required: true,
            validate: {
                validator: function(text) {
                    return text.length > 3
                },
                message: "Name provided is too short."
            }
        },
        slug: String,
        status: {
            type: String,
            required: true,
            validate: {
                validator: function(text) {
                    return text === 'pending' || 'active' || 'deactive'
                },
                message: "State error."
            }
        }
    },
    {versionKey: false}
);
schema.plugin(mongoosePaginate);
schema.index("name");
schema.index("slug");
const Category = mongoose.model("Category", schema);
module.exports = Category;